### ISSUE TITLE
Slightly funky styles when embedding tables in tables

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-techdocs#22]
http://origami-next-registry.herokuapp.com/

![screen shot 2014-12-02 at 19 55 11](https://cloud.githubusercontent.com/assets/825088/5269724/29ce626a-7a5d-11e4-962a-f67779d3d543.png)

Wonder if you'd mind me tweaking a few of the selectors around tables only to go one-table deep?

**Comment by kaelig** [comment]
@matthew-andrews is this still happening? (the link doesn't point to the Next registry anymore)

**Comment by kaelig** [comment]
Closing as a "won't fix" this hasn't come up in 4 months.
