### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-techdocs#28]

**Comment by AlbertoElias** [comment]
I think it was agreed that we're going to leave jQuery in, right @kaelig @triblondon?

**Comment by kaelig** [comment]
Personally I think it's fine!

**Comment by triblondon** [comment]
One reason I'd like to do this is that it makes polyfilling easier - if we don't have to figure out whether a problem is happening in jquery or the polyfill.

But it's a really low priority. Keep it around, I might do it on a plane or something.

**Comment by commuterjoy** [comment]
Passing highlight.js & jquery through babelify, debowerify, textrequireify and the gulp build browserify seem to take ages.

- 47 seconds for `require('o-techdocs');`
- 35s minus babelify
- 22s minus babelify + debowerify
- 19s minus babelify + debowerify + textrequireify

If I put the transforms back in again an stub out highlight and/or jquery ...

- 19s - no highlight.js
- 28s - no jquery 
- 9s - no highlight + no jquery (sort of bearable)

If I take out the transforms + the two big libraries build time is an acceptable 4 seconds.

Or can I instruct OBT to ignore the processing on specific files?

**Comment by commuterjoy** [comment]
Could just include the jquery as a global lib off the CDN?

**Comment by AlbertoElias** [comment]
Hopefully #37 will be merged soon which removes jQuery entirely
