### ISSUE TITLE
Use o-footer

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-techdocs#35]

**Comment by kaelig** [comment]
@triblondon any idea of what was the history behind the decision of not using the o-footer module initially?

**Comment by triblondon** [comment]
Different requirements, that's all.

**Comment by triblondon** [comment]
As a postscript to this, I don't object to using o-footer, but obviously not with the default content.  If the section lists were removed, and the copyright line used for the logo and help links, it could work.  But I don't think there's any particular need to change what we have.

**Comment by AlbertoElias** [comment]
@triblondon The reason would be the reason for Origami: consistency. The content for a blog, or for the homepage, or a developer page like the ones targeted by o-techdocs won't have the same content in the header or in the footer, but I think it would be nice if they had the same design

**Comment by triblondon** [comment]
OK, I've got no problem with it.  The content didn't seem quite compatible
to me, but if it can be used without too much attempting to put a square
peg in a round hole, feel free to do it.

However, on consistency, I'm more concerned with the JS in techdocs, which
violates the spec all over the place at the moment.  I'm working on fixing
that.

**Comment by AlbertoElias** [comment]
This can probably be closed
