### ISSUE TITLE
Request generator wizard

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-techdocs#39]
A utility that generates requests based on documented endpoints.

**Comment by kaelig** [comment]
Do you mean a sort of techdocs as a service? Just like the Sass and JS docs generator but with Markdown?

**Comment by samgiles** [comment]
No, this is to build (or reuse!) something similar to the playground built
here: http://markets.ft.com/research/webservices/companies/v1/docs

On Tue, Jun 9, 2015 at 3:52 PM, Kaelig <notifications@github.com> wrote:

> Do you mean a sort of techdocs as a service? Just like the Sass and JS
> docs generator but with Markdown?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-techdocs/issues/39#issuecomment-110391360>
> .
>



-- 
*Sam Giles*
Developer
FT Labs

For Origami questions: origami.support@ft.com

Number One Southwark Bridge, London SE1 9HL

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
