### ISSUE TITLE
Parse API Blueprint

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-techdocs#40]
Also might help implement #39.

So instead of the current markup table, you'd write API blueprint syntax, eg:

``` markdown
## My Message [/message]

### Retrieve a Message [GET]

+ Response 200 (text/plain)

        Hello World!

### Update a Message [PUT]

+ Request (text/plain)

        All your base are belong to us.

+ Response 204
```

And a Javascript lib would parse it and convert it into rendered documentation.  This would also then work with all the other API blueprint tools available in the community

**Comment by geek-caroline** [comment]
Would it be possible to somehow integrate this into inline comments that are held within the code for a service?

**Comment by triblondon** [comment]
Full details are at apiblueprint.org
