### ISSUE TITLE
Allow non-linking parent items in navlinks

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-techdocs#46]
Currently, if you have a **non-linking** parent item for a sub-nav list, it doesn't display correctly.

i.e. see how "Bar" isn't positioned correctly:

![image](https://cloud.githubusercontent.com/assets/250617/10453903/27a07ed6-71a8-11e5-9aac-fde5d41ab77b.png)

Here's how I want it to look (faked using devtools):

![image](https://cloud.githubusercontent.com/assets/250617/10453869/d136a91c-71a7-11e5-9d9c-1b7573c528b0.png)

The problem is the padding is only applied to `.o-techdocs-nav>li>a`.

It would be good if this padding was also applied to `.o-techdocs-nav>li>span`.

**Comment by expe** [comment]
It seems sensible to have a way to add a non-linking item.

I think It would be clearer to style this as `o-techdocs-nav__content`, do we think this would be more difficult for normal people to use?
```html
<ul class="o-techdocs-nav">
	<li class="o-techdocs-nav__item"><span class="o-techdocs-nav__content">Foo</span></li>
	<li class="o-techdocs-nav__item"><a class="o-techdocs-nav__content" href="#">Bar</a></li>
	<li class="o-techdocs-nav__item"><a class="o-techdocs-nav__content" href="#">Baz</a></li>
</ul>
```
```css
.o-techdocs-nav__content {
	padding: 6px 10px 6px 30px;
}
```

**Comment by triblondon** [comment]
Yeah, that seems sensible.

**Comment by notlee** [comment]
I'm closing this issue as we're deprecating `o-techdocs` in favor of `o-layout`. I'm pleased to report `o-layout` happens to cater for this 😄
