### ISSUE TITLE
why is aria-hidden styled to be display:none?

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-techdocs#47]
I'd like to use aria-hidden to hide an icon font icon from screen readers, but this is currently not working as i want it to because aria-hidden is styled to display:none. There are other (possibly more appropriate) ways to do the thing I want to do, but i'm curious to know what aria-hidden is styled to display:none here anyway.

https://github.com/Financial-Times/o-techdocs/blob/a5a7dbec3e881057429e97a02ec3ab180f3ebfa8/src/scss/_page.scss#L8

**Comment by expe** [comment]
This appears to be a W3C recommendation:
http://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden

Perhaps `role="presentation"` may be appropriate for case of an icon font:
http://www.w3.org/TR/wai-aria/roles#presentation

**Comment by onishiweb** [comment]
@alicebartlett is it worth looking into this again or should we give it some more consideration if/when we redesign/rewrite techdocs?
