### ISSUE TITLE
Overlapping navigation

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-techdocs#51]
The `o-techdocs-nav` overlaps the footer if its content is taller than the screen height (due to being fixed with `o-techdocs-nav--affix`). See the bottom-left of this screen grab:

![screen shot 2016-02-15 at 15 23 39](https://cloud.githubusercontent.com/assets/138944/13052714/483392e8-d3f8-11e5-9b1a-6bbe63327438.png)

(visible on http://origami.ft.com/docs/syntax/js/#syntax-convention-rules on a 13" monitor)

A possible solution would be to remove the fixed positioning once you scroll past the end of the container, positioning the navigation absolutely at the bottom of its parent. I can investigate if you think it's worth the extra complexity.

**Comment by notlee** [comment]
o-techdocs is deprecated
