### ISSUE TITLE
Dynamically built navigation items do not work when a base element is used on the page

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-techdocs#63]
Problem: When using a `<base>` element, the in-page navigation breaks due to ID based links getting prepended with the `<base>` elements `href` value.

The sub navigation which is built from the pages `<h2>` elements uses IDs for the value of the `href` attributes. When using a `<base>` element, all relative links get prepended with the base elements `href` value. Links which use IDs as their `href` value are captured as relative links, which means that they get the base elements `href` value prepended to them.

Proposed solution: When building the in-page navigation, create absolute urls instead of relative urls.

Here is a demo which uses tech-docs with a `<base>` element - http://output.jsbin.com/nibebutonu.

Here is the proposed solution (without techdocs to show the problem and solution on it's own) - http://jsbin.com/qedovudoga/edit?html,js,output

**Comment by onishiweb** [comment]
This might also be relevant to o-in-page-nav ?

**Comment by JakeChampion** [comment]
Looks like it!

**Comment by JakeChampion** [comment]
Closing the issue here in favour of https://github.com/Financial-Times/o-in-page-nav/issues/8 as o-techdocs will be using o-in-page-nav in the future.
