### ISSUE TITLE
Replace the sticky nav with o-inpage-nav

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-techdocs#67]
The sticky nav has been extracted to its own component, we should remove the nave from this, and replace it with a dependency on o-inpage-nav (https://github.com/financial-times/o-in-page-nav)

**Comment by notlee** [comment]
This was one of my new starter tasks I think? Well, I'm pleased to finally close it. 😁 We're deprecating `o-techdocs` in favor of `o-layout` and branded components.
